import React from 'react';
import type { Party } from '../types';

interface Props { partyB: Party; records: Party[]; listRef: React.RefObject<HTMLDivElement | null>; showList: boolean; onChange: (field: keyof Party, value: string) => void; onFocus: () => void; onSelect: (partyB: Party) => void; }
const PartyBFields: React.FC<Props> = ({ partyB, records, listRef, showList, onChange, onFocus, onSelect }) => {
  const matches = records.filter((record) => record.name.toLowerCase().includes(partyB.name.toLowerCase()));
  return <><div className="section-title">乙方資料</div><div className="form-group" style={{ position: 'relative' }}><label>公司名稱</label><input type="text" value={partyB.name} onChange={(e) => onChange('name', e.target.value)} onFocus={onFocus} autoComplete="off" />{showList && matches.length > 0 && <div className="party-b-dropdown" ref={listRef}>{matches.map((record, index) => <div key={`${record.name}-${index}`} className="party-b-option" onClick={() => onSelect(record)}><div className="c-name">{record.name}</div><div className="c-info">{record.contactPerson} | {record.phone}</div></div>)}</div>}</div><div className="form-row"><div className="form-group"><label>法代</label><input type="text" value={partyB.representative} onChange={(e) => onChange('representative', e.target.value)} /></div><div className="form-group"><label>統一編號</label><input type="text" value={partyB.taxId} onChange={(e) => onChange('taxId', e.target.value)} /></div></div><div className="form-group"><label>地址</label><input type="text" value={partyB.address} onChange={(e) => onChange('address', e.target.value)} /></div><div className="form-row"><div className="form-group"><label>電話</label><input type="text" value={partyB.phone} onChange={(e) => onChange('phone', e.target.value)} /></div><div className="form-group"><label>傳真</label><input type="text" value={partyB.fax} onChange={(e) => onChange('fax', e.target.value)} /></div></div><div className="form-row"><div className="form-group"><label>聯絡人</label><input type="text" value={partyB.contactPerson} onChange={(e) => onChange('contactPerson', e.target.value)} /></div><div className="form-group"><label>手機</label><input type="text" value={partyB.mobile} onChange={(e) => onChange('mobile', e.target.value)} /></div></div></>;
};
export default PartyBFields;
