import React from 'react';
import type { QuotationData } from '../types';
interface Props { data: QuotationData; onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void; }
const QuotationMetaFields: React.FC<Props> = ({ data, onChange }) => <>
  <div className="form-row"><div className="form-group"><label>業務人員 (自動記憶)</label><input type="text" name="salesName" value={data.salesName} onChange={onChange} /></div><div className="form-group"><label>業務電話 (自動記憶)</label><input type="text" name="salesMobile" value={data.salesMobile} onChange={onChange} /></div></div>
  <div className="form-row"><div className="form-group"><label>訂印日期</label><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><input type="text" name="orderYear" value={data.orderYear} onChange={onChange} style={{ width: '40px' }} /><span>/</span><input type="text" name="orderMonth" value={data.orderMonth} onChange={onChange} style={{ width: '30px' }} /><span>/</span><input type="text" name="orderDay" value={data.orderDay} onChange={onChange} style={{ width: '30px' }} /></div></div><div className="form-group"><label>交貨日期</label><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><input type="text" name="deliveryYear" value={data.deliveryYear} onChange={onChange} style={{ width: '40px' }} /><span>/</span><input type="text" name="deliveryMonth" value={data.deliveryMonth} onChange={onChange} style={{ width: '30px' }} /><span>/</span><input type="text" name="deliveryDay" value={data.deliveryDay} onChange={onChange} style={{ width: '30px' }} /></div></div></div>
  <div className="section-title">其他條款</div><div className="form-group"><label>其他備註</label><textarea name="remarks" value={data.remarks} onChange={onChange} rows={2} /></div><div className="form-row"><div className="form-group"><label>付款辦法</label><input type="text" name="paymentMethod" value={data.paymentMethod} onChange={onChange} /></div><div className="form-group"><label>交貨地點</label><input type="text" name="deliveryLocation" value={data.deliveryLocation} onChange={onChange} /></div></div>
</>;
export default QuotationMetaFields;
